### ISSUE TITLE
Error: HTTP 404: Not Found reading http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm

### ISSUE THREAD

**Issue by porunov** [saltstack-formulas/epel-formula#31]
Hello,

Sometimes I get this error:

```
----------
          ID: epel_release
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call                                            
                  **cdata['kwargs'])                                                                                                 
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper                                        
                  return f(*args, **kwargs)                                                                                          
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1277, in installed                                  
                  **kwargs)                                                                                                          
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 491, in _find_install_targets                       
                  cached_path = __salt__['cp.cache_file'](val, saltenv=kwargs['saltenv'])                                            
                File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 402, in cache_file                                  
                  result = _client().cache_file(path, saltenv)                                                                       
                File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 178, in cache_file                                  
                  return self.get_url(path, '', True, saltenv, cachedir=cachedir)                                                    
                File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 628, in get_url                                     
                  raise MinionError('Error: {0} reading {1}'.format(query['error'], url))                                            
              MinionError: Error: HTTP 404: Not Found reading http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm                                                                                                                           
     Started: 21:09:21.364717
    Duration: 1569.229 ms
     Changes:   
----------
          ID: set_pubkey_epel
    Function: file.replace
        Name: /etc/yum.repos.d/epel.repo
      Result: False
     Comment: One or more requisite failed: epel.epel_release
     Changes:   
----------
          ID: set_gpg_epel
    Function: file.replace
        Name: /etc/yum.repos.d/epel.repo
      Result: False
     Comment: One or more requisite failed: epel.epel_release
     Changes:
```

I don't know why it is happening. Sometimes I get this error and sometimes not. Do you know what it might be?

Best regards,
Alexandr

**Comment by ek9** [comment]
Looking at the formula, from now on RedHat (CentOS) releases you can enable linux by just installing `epel-release` package (`yum install epel-release -y`). Perhaps this formula can be updated to use that on at least CentOS boxes? It would also simplify the setup.

The problem you are experiencing is likely that a mirror isn't reachable at some times, as it's a slow server. Using `yum` would make sure that you use the mirror that is configured in your distribution.

**Comment by porunov** [comment]
@ek9 Thank you for explanation! With `yum` it works

**Comment by ek9** [comment]
I'll send a PR once I can recheck that it won't break things.

**Comment by PropTim** [comment]
whoopsie. I've just submitted a PR for the same thing. My bad.

T
--

**Comment by javierbertoli** [comment]
@porunov, @ek9, I think #36 fixes this issue. Can you check and close this issue if it's fixed?

**Comment by aboe76** [comment]
no comments so closing
